import { Article } from "@/types";

// Static images for articles
export const staticImages = {
  news: [
    "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&q=80",
    "https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=800&q=80",
    "https://images.unsplash.com/photo-1495020689067-958852a7765e?w=800&q=80",
    "https://images.unsplash.com/photo-1586339949916-3e9457bef6d3?w=800&q=80",
    "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&q=80",
    "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80",
  ],
  business: [
    "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80",
    "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80",
    "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800&q=80",
  ],
  sports: [
    "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80",
    "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80",
    "https://images.unsplash.com/photo-1551958219-acbc608c6377?w=800&q=80",
  ],
};

// Static articles for Most Read
export const staticMostReadArticles: Partial<Article>[] = [
  {
    id: "most-read-1",
    title: "Masbate City Announces New Infrastructure Projects",
    excerpt: "Mayor announces major road improvements and public facility upgrades across the city.",
    featuredImage: staticImages.news[0],
    views: 12500,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "masbate",
    author: "Masbate Today Staff",
    readingTime: 3,
  },
  {
    id: "most-read-2",
    title: "Local Fishermen Celebrate Record Catch Season",
    excerpt: "Masbate fishermen report best season in decades, attributing success to sustainable practices.",
    featuredImage: staticImages.news[1],
    views: 9800,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "masbate",
    author: "Maria Santos",
    readingTime: 4,
  },
  {
    id: "most-read-3",
    title: "New Tourism Initiative Launched in Masbate",
    excerpt: "Provincial government introduces new programs to boost local tourism and hospitality industry.",
    featuredImage: staticImages.news[2],
    views: 8700,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "masbate",
    author: "Juan dela Cruz",
    readingTime: 5,
  },
  {
    id: "most-read-4",
    title: "Education Department Opens New School Facilities",
    excerpt: "Three new school buildings inaugurated to accommodate growing student population.",
    featuredImage: staticImages.news[3],
    views: 7600,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "masbate",
    author: "Editorial Staff",
    readingTime: 3,
  },
  {
    id: "most-read-5",
    title: "Masbate Hosts Regional Sports Competition",
    excerpt: "Athletes from across the region gather for annual sports festival in Masbate City.",
    featuredImage: staticImages.sports[0],
    views: 6500,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "masbate",
    author: "Sports Reporter",
    readingTime: 4,
  },
];

// Static business articles
export const staticBusinessArticles: Partial<Article>[] = [
  {
    id: "business-1",
    title: "Local Market Sees Growth in Small Business Sector",
    excerpt: "New entrepreneurs open shops in Masbate City, contributing to local economic development.",
    featuredImage: staticImages.business[0],
    views: 3200,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "masbate",
    author: "Business Reporter",
    readingTime: 4,
    tags: ["business", "economy", "local"],
  },
  {
    id: "business-2",
    title: "Agricultural Exports Increase by 15% This Quarter",
    excerpt: "Masbate farmers benefit from improved trade relations and better harvest yields.",
    featuredImage: staticImages.business[1],
    views: 2800,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "masbate",
    author: "Agricultural Correspondent",
    readingTime: 5,
    tags: ["business", "agriculture", "exports"],
  },
];

// Static sports articles
export const staticSportsArticles: Partial<Article>[] = [
  {
    id: "sports-1",
    title: "Masbate Basketball Team Wins Regional Championship",
    excerpt: "Local team brings home the trophy after intense competition in regional finals.",
    featuredImage: staticImages.sports[0],
    views: 4500,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "masbate",
    author: "Sports Reporter",
    readingTime: 3,
    tags: ["sports", "basketball", "championship"],
  },
  {
    id: "sports-2",
    title: "Annual Rodeo Festival Attracts Thousands of Visitors",
    excerpt: "Masbate's famous rodeo festival showcases local cowboy culture and skills.",
    featuredImage: staticImages.sports[1],
    views: 5200,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "masbate",
    author: "Event Correspondent",
    readingTime: 4,
    tags: ["sports", "rodeo", "festival"],
  },
];

// Static editorial articles
export const staticEditorialArticles: Partial<Article>[] = [
  {
    id: "editorial-1",
    title: "The Future of Masbate: A Vision for Progress",
    excerpt: "An editorial on the importance of sustainable development and community engagement.",
    featuredImage: staticImages.news[4],
    views: 2100,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "blog",
    author: "Editor-in-Chief",
    readingTime: 6,
  },
  {
    id: "editorial-2",
    title: "Preserving Masbate's Cultural Heritage",
    excerpt: "A call to action for protecting and celebrating our local traditions and history.",
    featuredImage: staticImages.news[5],
    views: 1800,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "blog",
    author: "Cultural Editor",
    readingTime: 5,
  },
  {
    id: "editorial-3",
    title: "Building Bridges: Community Unity in Masbate",
    excerpt: "Reflections on how our community comes together in times of need and celebration.",
    featuredImage: staticImages.news[6],
    views: 1500,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "blog",
    author: "Opinion Writer",
    readingTime: 4,
  },
];

// Static Masbate News Articles
export const staticMasbateArticles: Partial<Article>[] = [
  {
    id: "masbate-1",
    title: "Masbate City Announces New Infrastructure Projects Worth ₱50 Million",
    excerpt: "Mayor announces major road improvements and public facility upgrades across the city, including new drainage systems and street lighting.",
    featuredImage: staticImages.news[0],
    views: 12500,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "masbate",
    author: "Masbate Today Staff",
    readingTime: 3,
  },
  {
    id: "masbate-2",
    title: "Local Fishermen Celebrate Record Catch Season",
    excerpt: "Masbate fishermen report best season in decades, attributing success to sustainable practices and favorable weather conditions.",
    featuredImage: staticImages.news[1],
    views: 9800,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "masbate",
    author: "Maria Santos",
    readingTime: 4,
  },
  {
    id: "masbate-3",
    title: "New Tourism Initiative Launched in Masbate Province",
    excerpt: "Provincial government introduces new programs to boost local tourism and hospitality industry, including training for tour guides.",
    featuredImage: staticImages.news[2],
    views: 8700,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "masbate",
    author: "Juan dela Cruz",
    readingTime: 5,
  },
  {
    id: "masbate-4",
    title: "Education Department Opens New School Facilities",
    excerpt: "Three new school buildings inaugurated to accommodate growing student population in rural areas of Masbate.",
    featuredImage: staticImages.news[3],
    views: 7600,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "masbate",
    author: "Editorial Staff",
    readingTime: 3,
  },
  {
    id: "masbate-5",
    title: "Masbate Hosts Regional Sports Competition",
    excerpt: "Athletes from across the region gather for annual sports festival in Masbate City, featuring basketball, volleyball, and athletics.",
    featuredImage: staticImages.sports[0],
    views: 6500,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "masbate",
    author: "Sports Reporter",
    readingTime: 4,
  },
  {
    id: "masbate-6",
    title: "Local Market Vendors See Increased Sales",
    excerpt: "Public market vendors report 20% increase in sales following recent renovations and improved facilities.",
    featuredImage: staticImages.news[7],
    views: 5400,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "masbate",
    author: "Business Correspondent",
    readingTime: 3,
  },
];

// Static National News Articles
export const staticNationalArticles: Partial<Article>[] = [
  {
    id: "national-1",
    title: "Philippine Economy Shows Strong Growth in Q1 2024",
    excerpt: "GDP growth exceeds expectations with 6.2% increase, driven by robust consumer spending and infrastructure investments.",
    featuredImage: staticImages.news[0],
    views: 15200,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "national",
    author: "National Correspondent",
    readingTime: 5,
  },
  {
    id: "national-2",
    title: "Senate Approves New Education Reform Bill",
    excerpt: "Legislation aims to improve quality of education nationwide with increased funding and teacher training programs.",
    featuredImage: staticImages.news[1],
    views: 13400,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "national",
    author: "Political Reporter",
    readingTime: 4,
  },
  {
    id: "national-3",
    title: "Tropical Storm Alert: PAGASA Issues Warning for Northern Luzon",
    excerpt: "Weather bureau advises residents to prepare as tropical depression approaches, expected to make landfall within 48 hours.",
    featuredImage: staticImages.news[2],
    views: 11800,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "national",
    author: "Weather Correspondent",
    readingTime: 3,
  },
  {
    id: "national-4",
    title: "Philippine Tourism Sets New Record with 5 Million Visitors",
    excerpt: "Tourism department announces milestone achievement, attributing success to improved infrastructure and marketing campaigns.",
    featuredImage: staticImages.news[3],
    views: 10200,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "national",
    author: "Tourism Reporter",
    readingTime: 4,
  },
  {
    id: "national-5",
    title: "Government Launches Digital Transformation Initiative",
    excerpt: "New program aims to digitize government services, making them more accessible to citizens across the country.",
    featuredImage: staticImages.news[4],
    views: 8900,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "national",
    author: "Technology Correspondent",
    readingTime: 5,
  },
  {
    id: "national-6",
    title: "Healthcare Workers Receive Salary Increase",
    excerpt: "Government implements new salary structure for healthcare professionals, addressing long-standing compensation concerns.",
    featuredImage: staticImages.news[5],
    views: 7600,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "national",
    author: "Health Reporter",
    readingTime: 4,
  },
];

// Static Blog/Opinion Articles
export const staticBlogArticles: Partial<Article>[] = [
  {
    id: "blog-1",
    title: "The Future of Masbate: A Vision for Progress",
    excerpt: "An editorial on the importance of sustainable development and community engagement in building a better Masbate.",
    featuredImage: staticImages.news[4],
    views: 2100,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "blog",
    author: "Editor-in-Chief",
    readingTime: 6,
  },
  {
    id: "blog-2",
    title: "Preserving Masbate's Cultural Heritage",
    excerpt: "A call to action for protecting and celebrating our local traditions and history for future generations.",
    featuredImage: staticImages.news[5],
    views: 1800,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "blog",
    author: "Cultural Editor",
    readingTime: 5,
  },
  {
    id: "blog-3",
    title: "Building Bridges: Community Unity in Masbate",
    excerpt: "Reflections on how our community comes together in times of need and celebration, strengthening our bonds.",
    featuredImage: staticImages.news[6],
    views: 1500,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "blog",
    author: "Opinion Writer",
    readingTime: 4,
  },
  {
    id: "blog-4",
    title: "The Role of Youth in Masbate's Development",
    excerpt: "Exploring how young people are driving innovation and positive change in our province.",
    featuredImage: staticImages.news[7],
    views: 1200,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "blog",
    author: "Youth Columnist",
    readingTime: 4,
  },
  {
    id: "blog-5",
    title: "Environmental Conservation: Our Responsibility",
    excerpt: "A perspective on the importance of protecting Masbate's natural resources and biodiversity.",
    featuredImage: staticImages.news[0],
    views: 1100,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "blog",
    author: "Environmental Advocate",
    readingTime: 5,
  },
  {
    id: "blog-6",
    title: "Economic Opportunities in Masbate",
    excerpt: "Analyzing potential growth sectors and investment opportunities that could benefit our local economy.",
    featuredImage: staticImages.business[0],
    views: 950,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "blog",
    author: "Economic Analyst",
    readingTime: 6,
  },
];

// Static Video Articles
export const staticVideoArticles: Partial<Article>[] = [
  {
    id: "video-1",
    title: "Masbate City Infrastructure Development Project",
    excerpt: "Watch our exclusive coverage of the groundbreaking ceremony for Masbate's new infrastructure projects worth ₱50 million.",
    featuredImage: staticImages.news[0],
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    videoEmbed: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    views: 15200,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "video",
    author: "Masbate Today Video Team",
    readingTime: 5,
    tags: ["infrastructure", "development", "masbate"],
    published: true,
    featured: true,
    sponsored: false,
    premium: false,
    content: "Full video coverage of the infrastructure development project announcement.",
    authorId: "video-team-1",
  },
  {
    id: "video-2",
    title: "Local Fishermen Celebrate Record Catch Season",
    excerpt: "Join us as we visit local fishing communities celebrating their best season in decades with sustainable fishing practices.",
    featuredImage: staticImages.news[1],
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    videoEmbed: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    views: 12800,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "video",
    author: "Maria Santos",
    readingTime: 6,
    tags: ["fishing", "sustainability", "community"],
    published: true,
    featured: false,
    sponsored: false,
    premium: false,
    content: "Documentary-style video covering the fishing community's success story.",
    authorId: "maria-santos",
  },
  {
    id: "video-3",
    title: "Masbate Tourism Initiative Launch",
    excerpt: "Provincial government introduces new tourism programs to boost local hospitality industry and attract more visitors.",
    featuredImage: staticImages.news[2],
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    videoEmbed: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    views: 11200,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "video",
    author: "Juan dela Cruz",
    readingTime: 4,
    tags: ["tourism", "hospitality", "masbate"],
    published: true,
    featured: false,
    sponsored: false,
    premium: false,
    content: "Video report on the new tourism initiatives and programs.",
    authorId: "juan-dela-cruz",
  },
  {
    id: "video-4",
    title: "Regional Sports Competition Highlights",
    excerpt: "Highlights from Masbate's hosting of the regional sports competition featuring basketball, volleyball, and athletics.",
    featuredImage: staticImages.sports[0],
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    videoEmbed: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    views: 9800,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "video",
    author: "Sports Reporter",
    readingTime: 5,
    tags: ["sports", "competition", "athletics"],
    published: true,
    featured: false,
    sponsored: false,
    premium: false,
    content: "Complete highlights and coverage of the regional sports competition.",
    authorId: "sports-reporter",
  },
  {
    id: "video-5",
    title: "Masbate Market Vendors Success Story",
    excerpt: "Public market vendors share their success stories following recent renovations and improved facilities.",
    featuredImage: staticImages.news[7],
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    videoEmbed: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    views: 8700,
    publishedAt: new Date(),
    createdAt: new Date(),
    category: "video",
    author: "Business Correspondent",
    readingTime: 4,
    tags: ["business", "market", "vendors"],
    published: true,
    featured: false,
    sponsored: false,
    premium: false,
    content: "Video interviews with market vendors about their improved business conditions.",
    authorId: "business-correspondent",
  },
];
